version: '3'
name: instagram_clone
services:
  instagram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/code
      - /code/venv