version: '3'
name: instagram_clone
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=instagram
      - MYSQL_USER=instagram
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}

  instagram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram
    ports:
      - 8000:5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=true
      - MAIL_USE_SSL=false
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - DATABASE_URL=mysql+pymysql://instagram:${DATABASE_PASSWORD}@mysql/instagram
    links:
      - mysql:dbserver
    depends_on:
      - mysql
    volumes:
      - .:/code
      - /code/venv

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - 8025:8025