version: '3'
name: microblog
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}

  microblog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microblog
    ports:
      - 8000:5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=true
      - MAIL_USE_SSL=false
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - DATABASE_URL=mysql+pymysql://microblog:${DATABASE_PASSWORD}@mysql/microblog
    links:
      - mysql:dbserver
      - elasticsearch
    depends_on:
      - mysql
      - elasticsearch
    volumes:
      - .:/code
      - /code/venv

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - 8025:8025