version: '3'
name: instagram_clone
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db_o396
      - MYSQL_USER=o396
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_HOST=mysql.mikr.us
      - MYSQL_PORT=3306

  instagram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagram
    expose:
      - 5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=true
      - MAIL_USE_SSL=false
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - DATABASE_URL=mysql+pymysql://o396:${DATABASE_PASSWORD}@mysql:3306/db_o396
    links:
      - mysql:dbserver
    depends_on:
      - mysql
    volumes:
      - .:/code
      - /code/venv

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - 8025:8025
 
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:20396
    depends_on:
      - instagram
