#!/bin/bash

echo CI_REGISTRY_USER=$CI_REGISTRY_USER  >> .env
echo CI_JOB_TOKEN=$CI_JOB_TOKEN  >> .env
echo CI_REGISTRY=$CI_REGISTRY  >> .env
echo CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE  >> .env

echo SECRET_KEY=$SECRET_KEY >> .env
echo DATABASE_PASSWORD=$DATABASE_PASSWORD >> .env
echo DATABASE_HOST=$DATABASE_HOST >> .env
echo UPLOADS_DEFAULT_DEST=$UPLOADS_DEFAULT_DEST >> .env