"""photo path

Revision ID: 9a1c698e05a8
Revises: 03734c5c88bf
Create Date: 2023-06-20 16:38:22.840952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1c698e05a8'
down_revision = '03734c5c88bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=140), nullable=True))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
